import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styled from "styled-components";
import Layout from '../components/Layout'
import { NextPage } from "next";
import Hero from "../components/Hero";
import Tenants from "../components/Tenants";
import Landlords from "../components/Landlords";
import Search from "../components/Search";
import Property from "../components/Property";
import Testimonials from "../components/Testimonials";
import Contact from "../components/Contact";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = ()=> {
  return (
    <>
    <Layout>
      <Head>
        <title>Home Rentals Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Main>
          <Hero/>
          <Tenants/>
          <Landlords/>
          <Search />
          <Property/>
          <Testimonials/>
          <Contact/>
        </Main>
    </Layout>
    </>
  );
}

export default Home

const Main = styled.main`
  max-width: 1440px;
`

const Test = styled.div`
  width: 2em;
  height: 2em;
  background: red;
`;
